# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Profesor')),
            ],
        ),
    ]
