# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20181105_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
