# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20181105_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codigo_interno',
            field=models.CharField(default='', max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestion.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
