# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20181106_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['departamento', 'codigo_interno']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'ordering': ['dia', 'bloque']},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['cedula']},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_de', to='gestion.Profesor'),
        ),
    ]
