# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20181121_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='jefe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_de', to='gestion.Profesor'),
        ),
    ]
