# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20181121_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas_laboratorio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_practica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_teoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='gestion.Asignatura'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='unidad_creditos',
            field=models.IntegerField(default=0),
        ),
    ]
