# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_profesor_usuario'),
        ('gestion', '0021_auto_20181122_1543'),
    ]

    operations = [
    ]
