# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_merge_20181125_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
