# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_ofertatrimestral'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProfesoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('TEO', 'Teoría'), ('PRA', 'Práctica'), ('OTR', 'Otro')], max_length=3)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Asignatura')),
                ('oferta_trimestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.OfertaTrimestral')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Profesor')),
            ],
        ),
    ]
