# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_auto_20181126_1926'),
        ('gestion', '0025_auto_20181204_0002'),
    ]

    operations = [
    ]
