# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_merge_20181205_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionprofesoral',
            old_name='final',
            new_name='es_final',
        ),
        migrations.RemoveField(
            model_name='ofertatrimestral',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ofertatrimestral',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='ofertatrimestral',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='ofertatrimestral',
            name='unidad_creditos',
        ),
        migrations.AddField(
            model_name='ofertatrimestral',
            name='es_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertatrimestral',
            name='trimestre',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
