# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_auto_20181206_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionprofesoral',
            name='tipo',
            field=models.CharField(choices=[('TEO', 'Teoría'), ('PRA', 'Práctica'), ('OTR', 'Otro')], default='TEO', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='ofertatrimestral',
            unique_together=set([('trimestre', 'departamento')]),
        ),
    ]
