# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_auto_20181206_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionprofesoral',
            name='es_preferida',
            field=models.BooleanField(default=False),
        ),
    ]
