# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_asignacionprofesoral_es_preferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo_interno',
            field=models.CharField(max_length=4, unique=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Departamento', verbose_name='Departamento asociado'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas_laboratorio',
            field=models.IntegerField(default=0, verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas_practica',
            field=models.IntegerField(default=0, verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas_teoria',
            field=models.IntegerField(default=0, verbose_name='Horas de Teoría'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre de la asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='gestion.Asignatura', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='unidad_creditos',
            field=models.IntegerField(default=0, verbose_name='Unidades de Crédito (U.C.)'),
        ),
        migrations.AddField(
            model_name='coordinacion',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, to='gestion.Asignatura'),
        ),
        migrations.AddField(
            model_name='coordinacion',
            name='coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Profesor'),
        ),
    ]
