# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_auto_20181206_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('asignaturas', models.ManyToManyField(blank=True, to='gestion.Asignatura')),
                ('coordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Profesor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
